DROP TABLE IF EXISTS `log`;
DROP TABLE IF EXISTS `user`;


CREATE TABLE `user` (
    `uid` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `active` BOOLEAN DEFAULT FALSE,
    `name` VARCHAR(40) NOT NULL,
    `createtime` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updatetime` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `iteration` INT UNSIGNED DEFAULT 0
);


CREATE TABLE `log` (
    `lid` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `uid` INT UNSIGNED DEFAULT NULL,
    `type` ENUM('USER_ADDED', 'USER_ACTIVE', 'USER_DEACTIVE', 'TRAIN', 'RECG_SUCCESS', 'RECG_FAILURE', 'REQUEST', 'REMOTE_OPEN') DEFAULT NULL,
    `img` LONGTEXT DEFAULT NULL,
    `data` TEXT DEFAULT NULL,
    `createtime` DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (uid) REFERENCES user(uid)
);